eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka

  instance:
    localhost
    
microservice:
  ceoart-firebase-service:
    endpoints:
      endpoint:
        uri: http://localhost:7003/firebase
